NAME: 'cam-cbs-drs_with_afa'
OUTPUT_DIR: './output/cifar100_im50'
SHOW_STEP: 100
SAVE_STEP: 5
VALID_STEP: 1
INPUT_SIZE: (224, 224)
COLOR_SPACE: 'RGB'


DATASET:
  DATASET: 'CRC'
  TRAIN_JSON: 'json_files/crc_train2.json'
  VALID_JSON: 'json_files/crc_val2.json'
  USE_CAM_BASED_DATASET: True
  CAM_DATA_JSON_SAVE_PATH: 'json_files/cam_json2.json'

NETWORK:
  PRETRAINED:  True
  PRETRAINED_MODEL: './output/cifar100_im50/first_stage_with_afa/models/best_model.pth'


BACKBONE:
  TYPE: 'afa'

MODULE:
  TYPE: 'GAP'

CLASSIFIER:
  TYPE: 'FC'
  BIAS: True

LOSS:
  LOSS_TYPE: 'CrossEntropy'

TRAIN:
  BATCH_SIZE: 128
  MAX_EPOCH: 40
  NUM_WORKERS: 16
  COMBINER:
    TYPE: 'default'
  OPTIMIZER:
    TYPE: 'SGD'
    BASE_LR: 0.001
    MOMENTUM: 0.9
    WEIGHT_DECAY: 2e-4
  LR_SCHEDULER:
    TYPE: 'warmup'
    LR_STEP: [20]
    LR_FACTOR: 0.01
    WARM_EPOCH: 5
  TENSORBOARD:
    ENABLE: True
  SAMPLER:
    TYPE: 'weighted sampler'
    WEIGHTED_SAMPLER:
      TYPE: 'balance'

  DISTRIBUTED: False
  SYNCBN: True

TEST:
  BATCH_SIZE: 64
  NUM_WORKERS: 8
  MODEL_FILE: 'best_model.pth'
  
   