NAME: 'first'
OUTPUT_DIR: './output/resnext50/'
SHOW_STEP: 100
SAVE_STEP: 5
VALID_STEP: 1
INPUT_SIZE: (224, 224)
COLOR_SPACE: 'RGB'


DATASET:
  DATASET: 'CRC'
  TRAIN_JSON: 'json_files/crc_train2.json'
  VALID_JSON: 'json_files/crc_val2.json'

BACKBONE:
  TYPE: 'resnext50'

MODULE:
  TYPE: 'GAP'

CLASSIFIER:
  TYPE: 'FC'
  BIAS: True

LOSS:
  LOSS_TYPE: 'CrossEntropy'

TRAIN:
  BATCH_SIZE: 128
  MAX_EPOCH: 100
  NUM_WORKERS: 8
  COMBINER:
    TYPE: 'default'
  OPTIMIZER:
    TYPE: 'SGD'
    BASE_LR: 0.01
    MOMENTUM: 0.9
    WEIGHT_DECAY: 1e-4
  LR_SCHEDULER:
    TYPE: 'warmup'
    LR_STEP: [60, 80]
    LR_FACTOR: 0.01
    WARM_EPOCH: 5
  TENSORBOARD:
    ENABLE: True
  SAMPLER:
    TYPE: 'default'

  DISTRIBUTED: False
  SYNCBN: True

# TRANSFORMS:
#   TRAIN_TRANSFORMS: ('random_crop', 'random_horizontal_flip')
#   TEST_TRANSFORMS: ()

TEST:
  BATCH_SIZE: 64
  NUM_WORKERS: 8
  MODEL_FILE: 'best_model.pth'
  TAU_NORM:
    USE_TAU_NORM: True
    TAU: 0.1