NAME: 'bsce'
OUTPUT_DIR: './output/crc/'
SHOW_STEP: 100
SAVE_STEP: 5
VALID_STEP: 1
INPUT_SIZE: (224, 224)
COLOR_SPACE: 'RGB'


DATASET:
  ROOT: 'dataset/crc/data3'
  DATASET: 'CRC'
  TRAIN_JSON: 'json_files/crc_train2.json'
  VALID_JSON: 'json_files/crc_test2.json'
  # IMBALANCECIFAR:
  #   RATIO: 0.01

BACKBONE:
  TYPE: 'res101'

MODULE:
  TYPE: 'GAP'

CLASSIFIER:
  TYPE: 'FC'
  BIAS: True

LOSS:
  LOSS_TYPE: 'BalancedSoftmaxCE'

TRAIN:
  BATCH_SIZE: 128
  MAX_EPOCH: 200
  NUM_WORKERS: 16
  COMBINER:
    TYPE: 'default'
  OPTIMIZER:
    TYPE: 'SGD'
    BASE_LR: 0.1
    MOMENTUM: 0.9
    WEIGHT_DECAY: 2e-4
  LR_SCHEDULER:
    TYPE: 'warmup'
    LR_STEP: [160, 180]
    LR_FACTOR: 0.01
    WARM_EPOCH: 5
  TENSORBOARD:
    ENABLE: True
  SAMPLER:
    TYPE: 'default'

  DISTRIBUTED: False
  SYNCBN: True

# TRANSFORMS:
#   TRAIN_TRANSFORMS: ('random_crop', 'random_horizontal_flip')
#   TEST_TRANSFORMS: ()

TEST:
  BATCH_SIZE: 128
  NUM_WORKERS: 8
  MODEL_FILE: 'best_model.pth'